# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: ./frontend/my-app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    volumes:
      - ./frontend/my-app:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev
volumes:
  node_modules:
    driver: local

